baseURL = "https://mikeruschak.com/"
locale = "en-US"
title = "Michael J. Ruschak"

[params]
    author = "Michael J. Ruschak"
    bio = "Full Stack Programmer, Swimmer, Kayaker, Hiker from Rochester, NY"
    year = "2018"
